// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://moopmmgfiyhrcckxykab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vb3BtbWdmaXlocmNja3h5a2FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzE1MzQsImV4cCI6MjA3MTc0NzUzNH0.HVEWevhjixdjynkTHEXAfg-ILg3IFz9Y79JBcRzLQN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});